### ISSUE TITLE
Wrong POS for fused det-noun pronouns

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_English#11]
The UD guidelines say that words like _someone_ and _anybody_ should be PRON, but we still tag them as NOUN, because they're all NN in the Penn Treebank.

indefinite pronouns: somebody, something, someone, anybody, anything, anyone
totality pronouns: everybody, everything, everyone
negative pronouns: nobody, nothing

**Comment by berzak** [comment]
There is a similar issue in the English-ESL annotations. I will fix it there for the next release.

Yevgeni
