### ISSUE TITLE
Some non-verbs have VerbForm feature

### ISSUE THREAD

**Issue by sebschu** [UniversalDependencies/UD_English#12]
(Reported by Bruno Guillaume via email)

Some tokens have a VerbForm feature with cat ≠ VERB or AUX,
You can see the 4 occurrences following this link: http://talc2.loria.fr/grew/?custom=57f65c7572395&corpus=UD_English-1.3

**Comment by dan-zeman** [comment]
While I do not know whether the English-specific guidelines allow this, in general the `VerbForm` feature indeed can occur with verbal `NOUN`s, participles tagged `ADJ` etc.
