### ISSUE TITLE
nmod or dobj; xcomp or dobj?

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_English#15]
I am currently looking into converting a german treebank and have a question about `nmod` and `dobj`.

How should the sentence _He belongs to the party._ be labeled; specifically how should _party_ be attached to _belongs_? In other examples from the English treebank containing _... belongs to ..._ or _... resorts to ..._ the latter part is always connected with `nmod`: `(He <nsubj belongs > (to <case the <det party))`. However, I think this doesn't capture the importance of _to the party_ because it isn't just modifying _belongs_; _to the party_ is a core dependent of _belongs_. I think the effect is even stronger with the sentence _He abides by the agreement_. It is very different from _He reads a book on friday._ where _on friday_ is connected with `nmod`.

In the German source grammar I am looking into right now, _to the party_ would be connected as a _prepositional object_, (The sentence would be _Er gehört zu der Partei._) this is the reason I thought of this.

Because of a similar reason I think _I consider him a fool._ should not be `(I <nsubj consider >dobj him >xcomp (a <det fool))` but `(I <nsubj consider >dobj him >iobj (a <det fool))` (instead of `xcomp` use `iobj`). _a fool_ would be an object in the German grammar I use.

**Comment by jnivre** [comment]
The correct relation used to be `nmod` but as of v2, which will be launched in about an hour, it is `obl`. A fundamental fact about the UD scheme is that we do not make a distinction between arguments and adjuncts, only between core arguments and oblique modifiers, where obliques can be either arguments or adjuncts. The core-oblique distinction is not about whether a dependent is part of the valency of the predicate, only about how it is grammatically encoded. A good place to start is probably here: http://universaldependencies.org/v2/core-dependents.html

**Comment by dan-zeman** [comment]
FWIW, the current UD German treebank analyzes _gehören zu NOUN_ as `nmod` (which means it will become `obl` in the next release).

**Comment by fhennig** [comment]
Okay I see, I was thinking about semantics too much, just from the syntactic structure it is pretty clear which label is correct. Thanks!
