### ISSUE TITLE
Treatment of "num year old noun" seems questionable

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_English#17]
For constructions like "8 year old daughter" UD_English currently has:

nmod:poss(daughter, my)
nummod(year, 8)
obl:npmod(old, year)
amod(daughter, old)
nsubj(loves, daughter)

The conversion of the old npmod to obl here seems questionable to me. Should it be that or something else (such as advmod)?

**Comment by nschneid** [comment]
Also worth considering the predicative form: "My daughter is 8 years old"

Because year(s) is tagged as a NOUN, I see the logic of `obl:npmod`. The [`advmod` documentation](http://universaldependencies.org/u/dep/advmod.html) states:

> Note that in some grammatical traditions, the term *adverbial modifier* covers constituents that function like adverbs regardless whether they are realized by adverbs, adpositional phrases, or nouns in particular morphological cases. We differentiate adverbials realized as adverbs (*advmod*) and adverbials realized by noun phrases or adpositional phrases (`obl`).

That said, perhaps `obl:advmod` would be a better name than `obl:npmod` for nouns functioning as amount/extent/cost adverbials.

**Comment by dan-zeman** [comment]
FWIW, in the data I annotated manually, I used `obl` only when it was modifying a clause. Under adverbs and adjectives that were not predicates, I used `nmod` instead. I was not sure about it though. I always thought we were only speaking about clauses when we first distinguished `obl` from `nmod`; but now I see in the documentation of `obl` that I was probably wrong.

**Comment by arademaker** [comment]
@dan-zeman what about the advcl ? In the matrix (http://universaldependencies.org/u/dep/index.html) it is the cell in the `Non-core dependents` row and `Clauses' column.

**Comment by dan-zeman** [comment]
`advcl` means that the dependent is clause. _8 year_ is not a clause, it's a noun phrase. Sorry if I'm missing what you're proposing.
