### ISSUE TITLE
The label of the clausal complement with "what"

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English#23]
When in a clausal complement and "what" as either subject or object in the clause, there seem 2 ways to annotate:

1. "what" is considered as the obj of the previous word, and the clausal complement is the acl:relcl of "what"; (see example 1)
2. the clausal complement is the ccomp of the previous word; (see example 2)

```
# sent_id = email-enronsent07_01-0085
# text = "We don't know why he did what he did, but we are eager to find out," Dunn said.
1	"	"	PUNCT	``	_	23	punct	_ SpaceAfter=No
2	We	we	PRON	PRP Case=Nom|Number=Plur|Person=1|PronType=Prs	5	nsubj	_ _
3	do	do	AUX	VBP Mood=Ind|Tense=Pres|VerbForm=Fin	5	aux	_ SpaceAfter=No
4	n't	not	PART	RB	_	5	advmod _	_
5	know	know	VERB	VB VerbForm=Inf	23	ccomp	_	_
6	why	why	ADV	WRB PronType=Int	8	advmod	_	_
7	he	he	PRON	PRP Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	8	nsubj	_	_
8	did	do	VERB	VBD Mood=Ind|Tense=Past|VerbForm=Fin	5	advcl	_	_
9	what	what	PRON	WP PronType=Int	8	obj	_	_
10	he	he	PRON	PRP Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	11	nsubj	_	_
11	did	do	VERB	VBD Mood=Ind|Tense=Past|VerbForm=Fin	9	acl:relcl	_ SpaceAfter=No

# sent_id = answers-20111108083850AAzIsFI_ans-0005
# text = Talk to your academic adviser, see what they recommend.
1	Talk	talk	VERB	VB Mood=Imp|VerbForm=Fin	0 root	_	_
2	to	to	ADP	IN	_	5	case	_	_
3	your	you	PRON	PRP$ Person=2|Poss=Yes|PronType=Prs	5	nmod:poss	_	_
4	academic	academic	ADJ	JJ Degree=Pos	5	amod	_	_
5	adviser	adviser	NOUN	NN Number=Sing	1	obl	_ SpaceAfter=No
6	,	,	PUNCT	,	_	1	punct	_	_
7	see	see	VERB	VB Mood=Imp|VerbForm=Fin	1 parataxis	_	_
8	what	what	PRON	WP PronType=Int	10	obj	_	_
9	they	they	PRON	PRP Case=Nom|Number=Plur|Person=3|PronType=Prs	10	nsubj _	_
10	recommend	recommend VERB	VBP Mood=Ind|Tense=Pres|VerbForm=Fin	7	ccomp	_ SpaceAfter=No
11	.	.	PUNCT	.	_	1	punct	_	_
```

Which one should be the more correct one, and how can we distinguish these 2 ways?

**Comment by nschneid** [comment]
I suspect the first sentence is incorrect and the second is correct, but someone else should confirm.

These free relative clause constructions can be tricky and probably deserve more documentation at [Complex Clauses](http://universaldependencies.org/u/overview/complex-syntax.html). Right now it only mentions clausal subjects.

Yesterday I heard a song lyric that would make a good example, as it combines a free relative clause with control: "I know who you want to take me home". I think the core structure would be:

ccomp(know, want)
nsubj(want, you)
obj(want, who)
xcomp(want, take)

**Comment by dan-zeman** [comment]
@nschneid : I agree with your song analysis, as well as with your assesment of @zhu-y11 's examples.

**Comment by sebschu** [comment]
I agree with @nschneid's song analysis but the English examples posted by  @zhu-y11 are both correct. 

The first one is a free relative, which we analyze with a relative clause attached to the wh-word (see http://universaldependencies.org/en/overview/specific-syntax.html#free-relatives and https://nlp.stanford.edu/pubs/demarneffe13more.pdf). 

The second one is just a clausal complement. These two cases can be a bit tricky to tell apart but as mentioned in the DepLing 2013 paper, there are some diagnostics, one of them is to replace the free relative with other sentential complements:

For the first sentence, we end up with ungrammatical sentences such as the following example:

    *We don't know why he did what thing he bought.
   
For the second sentence, this leads to grammatical sentences:

    Talk to your academic advisor, see which book they recommend.

**Comment by nschneid** [comment]
Thanks for the pointer, @sebschu! Are there plans to update the English-specific documentation for v2? I have trouble telling which parts of that page will need to change.

**Comment by sebschu** [comment]
Yes, sorry, I know that the documentation is currently in quite a bad state. There are definitely plans to update the English documentation at some point but we are also currently discussing whether the format of v1 (basically having a language-specific clone of the general guidelines) is really the best way to do this and I don't really think I can say when exactly this is going to happen (hopefully sometime over the summer!). If you have any input on what form/organization of documentation would be most useful, let us know!

**Comment by nschneid** [comment]
I don't have a specific recommendation but I have another data point: in the [PARSEME verbal MWE guidelines](http://parsemefr.lif.univ-mrs.fr/guidelines-hypertext/?page=home), just a few pages are language-specific, and all the pages allow toggling each language's examples via the toolbar at the top.
