### ISSUE TITLE
possible annotation error in guidelines

### ISSUE THREAD

**Issue by samuel-gibbon** [UniversalDependencies/UD_English#25]
Possible error in guidelines on free relatives <http://universaldependencies.org/en/overview/specific-syntax.html#free-relatives>

![image](https://user-images.githubusercontent.com/24224695/26957528-96830384-4d00-11e7-99c9-118d5b750029.png)

I think "who" should be nmod (or obl in v2), not dobj. In annotating the CHILDES corpus, we always attach prepositional phrases to their dependent with nmod (except in copular constructions such as "He is in the shower.", where the PP itself is the head), and this is true for stranded prepositions. So we would annotate...

1	oh	oh	INTJ	co	_	2	compound	_	_
2	no	no	INTJ	co	_	6	discourse	_	_
3	what	what	PRON	pro:wh	_	6	nmod	_	_
4	will	will	AUX	mod	_	6	aux	_	_
5	he	he	PRON	pro:sub	_	6	nsubj	_	_
6	write	write	VERB	v	_	0	root	_	_
7	with	with	ADP	prep	_	3	case	_	_
8	?	?	PUNCT	?	_	6	punct	_	_ 

1	what	what	PRON	pro:wh	_	4	nmod	_	_
2	are	be	AUX	aux	_	4	aux	_	_
3	you	you	PRON	pro	_	4	nsubj	_	_
4	crawling	crawl	VERB	part	_	0	root	_	_
5	on	on	ADP prep	_	1	case	_	_
6	?	?	PUNCT	?	_	4	punct	_	_

1	Adam	Adam	PROPN	n:prop	_	5	vocative	_	_
2	what	what	PRON	pro:wh	_	5	nmod	_	_
3	are	be	AUX	aux	_	5	aux	_	_
4	you	you	PRON	pro	_	5	nsubj	_	_
5	looking	look	VERB	part	_	0	root	_	_
6	for	for	ADP	prep	_	2	case	_	_
7	?	?	PUNCT	?	_	5	punct	_	_

Is this a simple error, or is there something else going on, i.e. do we have it wrong?

**Comment by nschneid** [comment]
Fixed by replacing `dobj` with `nmod`. @sebschu can you confirm?

**Comment by nschneid** [comment]
See also (89) in http://universaldependencies.org/en/overview/specific-syntax.html with regard to stranded prepositions (preposition stranding). Guessing this policy still applies to v2.

**Comment by sebschu** [comment]
@nschneid Yes, that's correct. Thanks for fixing the example.

**Comment by manning** [comment]
Confirmed correct.
