### ISSUE TITLE
Annotation disagreement of the copula's clausal complements

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English#28]
In the UD guidelines of [clausal object](http://universaldependencies.org/u/overview/complex-syntax.html#clausal-complements-objects) when the verb is the copula, ccomp is used with copulas in equational constructions involving "full clauses".

For clauses with "wh" words like what, how, why, where, ..., I'm not sure if they belong to the full clauses and should be labelled as ccomp of the copula, but based on my observations, there seems to be a clear disagreement of labels among clauses with these words (see examples below)

````
# sent_id = email-enronsent27_01-0019
# text = At least that is what I am thinking now.
1	At	at	ADV	RB	_	4	advmod	_	_
2	least	least	ADV	RBS	Degree=Sup	1	fixed	_	_
3	that	that	PRON	DT	Number=Sing|PronType=Dem	4	nsubj	_	_
4	is	be	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
5	what	what	PRON	WP	PronType=Int	8	obj	_	_
6	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	8	nsubj	_	_
7	am	be	AUX	VBP	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	8	aux	_	_
8	thinking	think	VERB	VBG	Tense=Pres|VerbForm=Part	4	ccomp	_	_
9	now	now	ADV	RB	_	8	advmod	_	SpaceAfter=No
10	.	.	PUNCT	.	_	4	punct	_	_

# sent_id = weblog-blogspot.com_dakbangla_20050311135387_ENG_20050311_135387-0004
# text = A key question is how they acquired the anthrax strain first isolated by the Texas Veterinary Medical Diagnostic Lab in 1980.
1	A	a	DET	DT	Definite=Ind|PronType=Art	3	det	_	_
2	key	key	ADJ	JJ	Degree=Pos	3	amod	_	_
3	question	question	NOUN	NN	Number=Sing	4	nsubj	_	_
4	is	be	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
5	how	how	ADV	WRB	PronType=Int	7	advmod	_	_
6	they	they	PRON	PRP	Case=Nom|Number=Plur|Person=3|PronType=Prs	7	nsubj	_	_
7	acquired	acquire	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	4	ccomp	_	_
8	the	the	DET	DT	Definite=Def|PronType=Art	10	det	_	_
9	anthrax	anthrax	NOUN	NN	Number=Sing	10	compound	_	_
10	strain	strain	NOUN	NN	Number=Sing	7	obj	_	_

# sent_id = newsgroup-groups.google.com_civicamerican_22c54c292026bfd2_ENG_20060128_072400-0037
# text = AND THAT IS WHY ALL AMERICANS SHOULD OPPOSE THE NOMINATION OF SAMUEL ALITO.
1	AND	and	CCONJ	CC	_	4	cc	_	_
2	THAT	that	PRON	DT	Number=Sing|PronType=Dem	4	nsubj	_	_
3	IS	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	4	cop	_	_
4	WHY	why	ADV	WRB	PronType=Int	0	root	_	_
5	ALL	all	DET	DT	_	6	det	_	_
6	AMERICANS	AMERICANS	PROPN	NNPS	Number=Plur	8	nsubj	_	_
7	SHOULD	should	AUX	MD	VerbForm=Fin	8	aux	_	_
8	OPPOSE	oppose	VERB	VB	VerbForm=Inf	4	acl:relcl	_	_
9	THE	the	DET	DT	Definite=Def|PronType=Art	10	det	_	_
10	NOMINATION	nomination	NOUN	NN	Number=Sing	8	obj	_	_
11	OF	of	ADP	IN	_	12	case	_	_
12	SAMUEL	SAMUEL	PROPN	NNP	Number=Sing	10	nmod	_	_
13	ALITO	ALITO	PROPN	NNP	Number=Sing	12	flat	_	SpaceAfter=No
14	.	.	PUNCT	.	_	4	punct	_	_

# sent_id = answers-20111108072912AAccket_ans-0011
# text = This is where you can get AND change express train tickets.
1	This	this	PRON	DT	Number=Sing|PronType=Dem	3	nsubj	_	_
2	is	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	3	cop	_	_
3	where	where	ADV	WRB	PronType=Int	0	root	_	_
4	you	you	PRON	PRP	Case=Nom|Person=2|PronType=Prs	6	nsubj	_	_
5	can	can	AUX	MD	VerbForm=Fin	6	aux	_	_
6	get	get	VERB	VB	VerbForm=Inf	3	acl:relcl	_	_
7	AND	and	CCONJ	CC	_	8	cc	_	_
8	change	change	VERB	VB	VerbForm=Inf	6	conj	_	_
9	express	express	ADJ	JJ	Degree=Pos	10	amod	_	_
10	train	train	NOUN	NN	Number=Sing	11	compound	_	_
11	tickets	ticket	NOUN	NNS	Number=Plur	6	obj	_	SpaceAfter=No
12	.	.	PUNCT	.	_	3	punct	_	_
````

Clauses with **what** and **how** are labelled as ccomp of copula where the copula is the root, whereas for **why** and **where** are labelled as root, and the clauses are acl:relcl, copula being cop relation to the root.

I am wondering why UD made these differences among "wh" words and which one is the preferred/correct one?

**Comment by nschneid** [comment]
Related to #23

**Comment by zhu-y11** [comment]
@nschneid I really cannot tell where the difference is among **how** and **where**\\**why**. I think they should at least have the same constructions for this situation.

**Comment by amir-zeldes** [comment]
I agree that they should be the same, and I would very much like to vote against the copula + ccomp option in general. I don't think copulas take ccomp in that way: the clause simply stands in for the nominal predicate (so it is more like a nominative than an accusative, if that makes sense).

I see the reasoning behind the guideline's explanation that the alternative is bad because you can have two `nsubj` relations, but it is actually not so difficult to see which is which: in 'double subject' cases you generally have a `mark` going to the embedded verb and bracketing in its subject:

It's not [that I can't go]
nsubj(go, I)
nsubj(go, it)

and even if you don't have a mark, I can't think of a language where the embedded subject is not closer to the embedded predicate than the copula subject (i.e. go is closer to `I`, therefore `it` must be the matrix subject). 

But even if we feel this needs to be marked explicitly, I think subtyping or a morph feature are better than `ccomp`. In my opinion the adverbial issue we're seeing here is just another motivation to change the guideline.

**Comment by zhu-y11** [comment]
@amir-zeldes Thanks for your answer and explanation, and I understand and agree with what you said.

@nschneid @amir-zeldes So as we are labelling some new data with UD conventions currently, which way would be better (may be for the future us and guideline change) way for **how**, **where** and **why** since they don't have the same constructions?

**Comment by nschneid** [comment]
I also don't see why *how*, *where*, and *why* shouldn't all be treated the same. Paging @sebschu :)

**Comment by nschneid** [comment]
@manning?

**Comment by sebschu** [comment]
Sorry for the late reply, but I think these are all free relatives, and hence should be analyzed as in the sentence _ AND THAT IS WHY ALL AMERICANS SHOULD OPPOSE THE NOMINATION OF SAMUEL ALITO._

I'll fix that in the data.
