### ISSUE TITLE
Which one is the correct annotation for "at first"

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English#30]
Mainly 2 ways to annotate "at first" in UD, which one would be more correct?
1. case(first, at) obl/nmod(predicate, first)
````
# sent_id = answers-20111108092643AAXe4lD_ans-0010
# text = At first it was all cool and all.
1	At	at	ADP	IN	_	2	case	_	_
2	first	first	ADV	RB	_	6	obl	_	_
3	it	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	6	nsubj	_	_
4	was	be	AUX	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	6	cop	_	_
5	all	all	ADV	RB	_	6	advmod	_	_
6	cool	cool	ADJ	JJ	Degree=Pos	0	root	_	_
7	and	and	CCONJ	CC	_	8	cc	_	_
8	all	all	DET	DT	_	6	conj	_	SpaceAfter=No
9	.	.	PUNCT	.	_	6	punct	_	_
````
2. advmod(first, at) advmod(predicate, first)
````
# sent_id = weblog-blogspot.com_rigorousintuition_20050518101500_ENG_20050518_101500-0003
# text = ("At first I hid a lot.
1	(	(	PUNCT	-LRB-	_	6	punct	_	SpaceAfter=No
2	"	"	PUNCT	``	_	6	punct	_	SpaceAfter=No
3	At	at	ADV	RB	_	4	advmod	_	_
4	first	first	ADV	RB	_	6	advmod	_	_
5	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	6	nsubj	_	_
6	hid	hide	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	0	root	_	_
7	a	a	DET	DT	Definite=Ind|PronType=Art	8	det	_	_
8	lot	lot	NOUN	NN	Number=Sing	6	obl:npmod	_	SpaceAfter=No
9	.	.	PUNCT	.	_	6	punct	_	_
````
I'm for the first one.

**Comment by nschneid** [comment]
> I'm for the first one.

Me too. Handling certain preposition constructions differently would open up a can of worms.

I happen to be working on PP idioms, and there are various other P+Adj idioms in English, including:
* at least/most
* at best/worst
* at all, above all, after all (perhaps all is actually a DET—in any case, not a prototypical noun)
* by far
* for free

**Comment by zhu-y11** [comment]
@nschneid Thanks very much! Is there some reference or paper on how to categorize them?

**Comment by nschneid** [comment]
[Baldwin et al. 2006](http://people.eng.unimelb.edu.au/tbaldwin/pubs/prepbook2005-determinerlessPP.pdf) might be useful.

**Comment by zhu-y11** [comment]
@nschneid Got it! :) Many thanks!
