### ISSUE TITLE
How to analyze "Reading is to the mind what exercise is to the body"

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English#31]
I get the meaning of it, but don't know who to analyze it. Could somebody tell me, don't know if it is a right place to raise such question. Thanks! :)

**Comment by dan-zeman** [comment]
nsubj(what, exercise)
cop(what, is-8)
obl(what, body)

nsubj(is-2, reading)
obl(is-2, mind)
ccomp(is-2, what)

The reason why the first clause is not analyzed as a non-verbal predicate with a copula is that the non-verbal predicate is represented by the second (nested) clause. See http://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses, e.g., the example 17 of class 1b.

**Comment by zhu-y11** [comment]
@dan-zeman thanks for your help! So the sentence is basically "Reading is what exercise is", now I got it. :)
