### ISSUE TITLE
How to deal with special nominal phrases with front head word

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English#32]
For nominal phrases like

- miss universe
- mother panda

where according to the common knowledge or the context, the head word is the first one (miss & mother). In this case, how to annotate such nominals? 

I've come up with 2 constructions:
compound(miss, universe) (very seldom see "compound" goes backwards)
or
nmod:npmod(miss, universe)

Which one would be more correct, or is there another way to annotate them? Thanks! :)

**Comment by sebschu** [comment]
What makes you so sure that the first token is the head in both cases? Especially _mother panda_ seems like a perfectly fine compound with _panda_ as the head to me. Do you have any evidence for _mother_ being the head?

For _Miss Universe_, I agree that Miss is probably the head and I also wouldn't analyze it the same way as a regular name like _Miss Smith_. But it looks very much like a compound to me, so I'd go with `compound(Miss, Universe)`. The fact that compounds are often headed by the last noun in English is just a tendency and it is perfectly compatible with the guidelines to make the first token the head.

**Comment by zhu-y11** [comment]
@sebschu thanks for your reply! :) So *compound* is rather flexible, and can go in either direction, and I think it is clear for *Miss Universe* to me.

As for *mother panda*, I am actually not sure about that. For me the component words are equally important representing different aspects of the characteristics of the nominal, and it seems to me that making *mother* would be better or more comfortable than *panda* for me, because in Chinese the order is actually reversed, translated as *panda mother* and *universe lady* literally. Is there also *panda mother* in English?

**Comment by sebschu** [comment]
> Is there also panda mother in English?

Yes, there is. I think the meaning of the two versions varies a bit but both of them exist (and, if we can trust the number of Google results, both seem approximately equally frequent)

**Comment by zhu-y11** [comment]
@sebschu For Google it seems to me that they don't actually differentiate the order for such phrases a lot? So for *panda mother* in English, mother would be the head? It is interesting because in Chinese it sounds very awkward to say *mother panda* (probably ungrammatical?) and we would only use *panda mother*.

**Comment by nschneid** [comment]
The "panda mother"/"mother panda" reminds me of exocentric compounds like "student teacher" (though there the order is fixed: "teacher student" is not used for an individual).

But since UD is a way of annotating syntax, not semantics, I think it's safest to go with the generalization that in an English compound of two nouns, the second one is always the head.

**Comment by sebschu** [comment]
> So for panda mother in English, mother would be the head?

Yes, I would say so.

I'd say (but I'm also not a native English speaker) that the difference between _mother panda_ and _panda mother_ is that in the first case _mother_ acts somewhat  like a modifier of _panda_, so one uses this phrase to differentiate from other pandas, e.g., the child. In the second case, _panda mother_, the focus is more on _panda_ and you would use this phrase to make a contrast to other mothers, e.g., _lion mothers_. So in the second case _panda_ acts somewhat like a modifier to _mother_. Does that make sense?

**Comment by nschneid** [comment]
Yes, I think that may be the case, at least to an extent, but there are a lot of contexts where the difference is not salient. :)

**Comment by nschneid** [comment]
What is the argument for making "Miss" the head in "Miss Universe"? How is it different from "Miss Smith"?

**Comment by sebschu** [comment]
@nschneid: My rationale was that you can have _the Miss Universe_ or _the Miss_, but you can't do that with _Miss Smith_.

**Comment by nschneid** [comment]
Really? "The Miss" sounds pretty strange to me in either case.

**Comment by nschneid** [comment]
(Speaking as a nonexpert on pageants, that is.)

**Comment by sebschu** [comment]
:D 

And you are right about _the miss_ -- that is weird (don't know why this sounded okay to me intially...). After reconsidering my initial hesitations, maybe the right thing would indeed be to just analyze it as `flat(miss, universe)`, which would be analogous to actual names like _Miss Smith_? Then we also don't have to worry which of the two should be the head :)

**Comment by nschneid** [comment]
Yeah, `flat` sounds good to me.

**Comment by sebschu** [comment]
Okay, then to recap, the slightly incoherent discussion:

 * _Miss Universe_ should be analyzed as `flat(Miss, Universe)`.
 * _mother panda_ should be analyzed as `compound(panda, mother)`.
