### ISSUE TITLE
UD 2.0 documentation for comparative constructions and case government of adjectives

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_English#36]
It is said here http://universaldependencies.org/u/dep/nmod.html

> New from v2: The nmod relation was previously used also for nominal dependents of verbs, adjectives, and adverbs. The latter are now covered by the new obl relation.

but it seems that in the comparative construction we go on with nmod for the nominal dependent of an adjective
nmod(smarter.than-John)
or nmod:comp in some languages.

*2*

As for the argument constructions of adjectives and adverbs, in my view, the documentation [u] overlooks the case of case govenment,
cf. Russian examples 
(1) dostojnyj.ADJ doverija.Gen
worthy.ADJ trust.Gen
Here, nor "trust" can be treated as "corresponding to an adverbial attaching to a verb", neither "worthy" can be called predicate, in the attributive position. 
Other examples:
(2) dovolnyj.ADJ rezultatami.INS
happy.ADJ with-results.INS
(3) vernyj.ADJ dolgu.DAT
faithful.ADJ to-duty.DAT
(4) sklonnyj.ADJ ko.ADP lzhi.NOUN.Dat
inclined to lies

Do we annotate all these cases as obl 
a) in both attributive and predicative uses?
and b) ignoring the difference between "core" arguments and "free" (adverbial-like) modifiers, as in
(5) obl(faithful, to-duty.Dat) 
obl(faithful, first-of-all.PP)

*3*

The documentation of obj and iobj only mentions "The object of a verb ....". However, in many treebanks participles are labeled ADJ. It seems that participles should be discussed on these pages.

**Comment by sebschu** [comment]
> but it seems that in the comparative construction we go on with nmod for the nominal dependent of an adjective
nmod(smarter.than-John)
or nmod:comp in some languages.

Where did you find this information? This should be `obl(smarter, John)` (also somewhat related: #29).

> Do we annotate all these cases as obl
a) in both attributive and predicative uses?
and b) ignoring the difference between "core" arguments and "free" (adverbial-like) modifiers, as in
(5) obl(faithful, to-duty.Dat)
obl(faithful, first-of-all.PP)

Yes.

> It seems that participles should be discussed on these pages.

Yes, good point. But I think @jnivre and others are currently restructuring the documentation, so this  change probably has to wait until we are releasing the new documentation.

**Comment by jnivre** [comment]
We definitely have more work to do when it comes to arguments/modifiers of predicates that are not finite verbs. The restructuring of the universal guidelines is on its way but will not happen before the next release.

**Comment by dan-zeman** [comment]
As for comparative constructions, there is a working group on comparatives (currently consisting of me, but open to others), and a draft of the new documentation is here:

http://universaldependencies.org/workgroups/comparatives.html

(Note that all words in all non-English examples have a Gloss attribute in the MISC column of the CoNLL-U format. The current version of Brat visualization does not show it in the diagrams but it can be seen by hovering the mouse over the word.)

**Comment by jnivre** [comment]
I just read the draft and find it excellent. A very good model of what our new guideline docs should be like. I think you should advertise it on the UD list and invite comment. Ideally, we should have a commenting function on each working group page, but perhaps we can create a GitHub issue for each working group and collect the comments there.

The only thing I would like to add is an elliptic example that uses the orphan relation, because I think that is a real possibility here. For example, something like:

Dan plays badminton better than Joakim tennis.

I am not sure that this is okay in English, but the corresponding sentence in Swedish seems fine to me:

Dan spelar badminton bättre än Joakim tennis.

**Comment by nschneid** [comment]
> Dan plays badminton better than Joakim tennis.
> 
> I am not sure that this is okay in English, but the corresponding sentence in Swedish seems fine to me:

Doesn't work for me, though it's similar to *Dan plays badminton and Joakim, tennis*, which is fine.

**Comment by dan-zeman** [comment]
Thanks, one more reason to use the Swedish version (which I would use anyway because I think there are no Swedish examples yet) :-)

**Comment by dan-zeman** [comment]
@nschneid : What would be a fluent English translation that would work for you?

**Comment by nschneid** [comment]
Insert "does" or "plays" between Joakim and tennis.

**Comment by jnivre** [comment]
What about with an oblique?

Nathan gives more to the Red Cross than Dan to Amnesty International.

**Comment by ftyers** [comment]
@jnivre it's a bit awkward with longer NPs (and maybe with different definiteness) but something like: _Nathan gives more to you than Dan to me_ definitely works.

**Comment by jnivre** [comment]
And I bet this is worse:

Nathan gives you more than Dan me

More evidence for the significance of the core-oblique distinction. :)

**Comment by dan-zeman** [comment]
Czech dative works fine here:

_Nathan mi dal víc než já tobě._

lit. “Nathan me gave more than I you.”

**Comment by jnivre** [comment]
Well, the dative is only semi-core. :)

**Comment by dan-zeman** [comment]
I have created the issue on comparatives in the main repository:
https://github.com/UniversalDependencies/docs/issues/507
