### ISSUE TITLE
NumType incorrectly assigned for German decimals

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English#483]
These numbers should be `NumType=Frac` instead of `NumType=Card`:
```
ERROR: Sentence answers-20111108024148AAO8oFI_ans-0010 token 3 -- CD/NumForm=Digit/NumType=Card lemma '3.40' does not match cardinal-number applied to form '3,40', expected '340'
ERROR: Sentence answers-20111108024148AAO8oFI_ans-0010 token 9 -- CD/NumForm=Digit/NumType=Card lemma '7.5' does not match cardinal-number applied to form '7,5', expected '75'
```

The following should also have the lemma `3.`:
```
ERROR: Sentence email-enronsent00_02-0032 token 10 -- CD/NumForm=Digit/NumType=Card lemma '3,' does not match cardinal-number applied to form '3,', expected '3'
```

**Comment by nschneid** [comment]
The third one is from an oddly spelled sentence:

> I am expecting to pay something in the $3,to $5,000 range.

I guess the "000" got deleted (or was omitted to save space). Shouldn't the lemma be "3" as if it were "3 to 5 thousand"?

**Comment by rhdunn** [comment]
That works for me. I've only done a cursory analysis of these, so some of my assignments may be wrong.

**Comment by rhdunn** [comment]
In that case, it would also need a `CorrectForm` annotation.

**Comment by nschneid** [comment]
Hmm, it would be nonstandard to write "$3 to $5,000 range" as well. I'll mark it as a typo of "$3,000".

**Comment by AngledLuffa** [comment]
I wouldn't consider that a typo.  At most it's a common colloquial way of
expressing a range

**Comment by nschneid** [comment]
I don't think I've seen it before. Certainly the missing space is a typo.

**Comment by AngledLuffa** [comment]
I'm just thinking that ranges get expressed as 4 to 5 million, 4 to 5
thousand, etc pretty often in spoken English when trying to express
possible ranges for the price of something

**Comment by nschneid** [comment]
Yes but not with a repeated dollar sign in text (that I know of)
