### ISSUE TITLE
Fix POS mapping of WDT

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_English#7]
We didn't fix up the POS mapping of WDT for v. 1.2. As noted in UniversalDependencies/docs#223, instances of _that_ and _which_ which stand alone as a nominal should be mapped to PRON not DET, just as we have done for things tagged DT in the original.

**Comment by ngiordani** [comment]
Then the change log may be wrong, because I thought Sebastian said those
were fixed... I put it in the list of changes

**Comment by manning** [comment]
I think the readme is okay, if slightly overclaiming. In general this was fixed up for cases of demonstratives like this/these/that/those, namely the ones that have tag DT in the EWT. Just not those which have tag WDT.

**Comment by ngiordani** [comment]
Ah, I see. Well, I think it's still ok to change it if you want to be more
specific. I didn't know about this distinction.

N.

**Comment by jnivre** [comment]
I think the README is fine as well, even though it is less exact than it could have been (which is true of most READMEs, by the way). More importantly, the release package has now been uploaded to Lindat, so it would require a major effort to change the README for v1.2. Hardly worth it, I would say. :)

**Comment by ngiordani** [comment]
Oh, absolutely. I didn't realize the release package was ready!
